---
#title: "STAT 327 Homework 3"
#output: html_document
---

#We'll grade your homework by

#* opening your "hw3.Rmd" file in RStudio
#* clicking "Knit HTML"
#* reading the HTML output
#* reading your "hw3.Rmd"

#You should write R code anywhere you see an empty R code chunk. You
#should write English text anywhere you see "..."; please surround it
#with doubled asterisks so that it will show up as boldface
#and be easy for us to find.

#Include reasonable labels (titles, axis labels, legends, etc.) with
#each of your graphs.

Name: **Yingyuan Zhang**

Email: **zhang963@wisc.edu**

#We'll use data on housing values in suburbs of Boston. They are in an
#R package called "MASS." (An R package is a collection of code,
#data, and documentation. "MASS" refers to the book "Modern Applied
#Statistics with S." R developed from the earlier language, S.) The
#MASS package comes with the default R installation, so it's already on
#your computer.  However, it's not loaded into your R session by
#default. So we'll load it via the require() command 
#(there's nothing for you to do here):


require("MASS")
data("Boston")


#Run ?Boston (outside this R Markdown document) to read the help page for the Boston data frame.

#Convert the chas` variable to a factor with labels "off" and "on" (referring to the Charles river).


Boston$chas = factor(Boston$chas, levels=c("0", "1"), labels=c("off", "on"))

#How many rows are in the Boston data frame? How many columns?

dim(Boston)[1]
dim(Boston)[2]

#What does a row represent?

**Returns a matrix of integers indicating their row number in a matrix-like object, or a factor indicating the row labels.**

#What does a column represent?

**Returns a matrix of integers indicating their column number in a matrix-like object, or a factor indicating the column labels.**

#Make a density plot (with rug) of tax rates.

plot(density(Boston$tax))
rug(Boston$tax)

#Describe the shape of the distribution of tax rates.
**2 peaks**

#Note that the distribution shape doesn't make sense in light of the rug representation of the data. Make a histogram of the tax rates.

hist(Boston$tax)

#Why is the second peak of the density plot so large? In what way is the rug representation of the data inadequate? Write a line or two of code to figure it out, and then explain it.

hist(Boston$tax)
**There are many numbers on a specific point, which is likely to be between 600 and 800.**

#Make a barplot of "chas".

counts = table(Boston$chas); barplot(counts)

#How many neighborhoods are on the Charles river?

number=length(which(Boston$chas=="on"))

#Make a single graph consisting of three plots: 

#* a scatterplot of "nox" on the y-axis vs. "dis" on the x-axis 
#* a (vertical) boxplot of "nox" left of the scatterplot's y-axis
#* a (horizontal) boxplot of "dis" below the scatterplot's x-axis

#Hint: use layout with a 4x4 matrix, using the top-right 3x3 #corner
#for the scatterplot, leaving the bottom-left 1x1 corner blank, and
#using the other parts for the boxplots.

#(An optional challenge, worth 0 extra credit points: remove the axis
#and plot border from each boxplot.)
m=matrix(c(1,3,3,3,1,3,3,3,1,3,3,3,0,2,2,2),nrow=4,ncol=4)
layout(m)
boxplot(Boston$nox)
boxplot(Boston$dis, horizontal = TRUE)
plot(Boston$dis,Boston$nox)

#Look into the highest-crime neighborhood by making a single graph of one column of three rows:

#* Find the row number, r, of the neighborhood with the highest "crim".
#* Make a density plot of "crim". Include a rug to show the data.
#* Add a red circle at (x, y) = (max crime rate, 0) to make this maximum crime rate stand out.
#* Make a density plot with rug of "medv", adding a red circle at (x, y) = (medv[r], 0) to see what medv corresponds to the highest crime rate.
#* Repeat the last step for "ptratio".

r=which(Boston$crim == max(Boston$crim))

plot(density(Boston$crim));rug(Boston$crim)
points(Boston$crim[r],0,pch=1,col="red")
plot(density(Boston$medv));rug(Boston$medv)
points(Boston$medv[r],0,pch=1,col="red")
plot(density(Boston$ptratio));rug(Boston$ptratio)
points(Boston$ptratio[r],0,pch=1,col="red")

#What do you notice about the ptratio and medv for the highest-crime neighborhood?

**They are negative correlated.**